# This file was generated by GoReleaser. DO NOT EDIT.
class DegaServer < Formula
  desc ""
  homepage "https://degacms.com"
  version "0.3.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/factly/dega-server/releases/download/0.3.1/dega-server_0.3.1_macOS_64-bit.tar.gz"
    sha256 "21e12e2d7ac6a94d9ef75601e7f217d525c73ee759ca12fb08b022a5eecb021a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/factly/dega-server/releases/download/0.3.1/dega-server_0.3.1_linux_64-bit.tar.gz"
      sha256 "cf09cb14602851c16b9f9090e9df8b8ad85c6621a2f3997abbc292e655754094"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/factly/dega-server/releases/download/0.3.1/dega-server_0.3.1_linux_arm64.tar.gz"
        sha256 "ec03b5e97868f9fdc027e8f11f7af240781404d5026f0440b970640e8d4d41c8"
      else
        url "https://github.com/factly/dega-server/releases/download/0.3.1/dega-server_0.3.1_linux_armv6.tar.gz"
        sha256 "543fed6823eb843bc4cc7b9d8787d9a77feb2d78c89e08b8ab3b18a5278a17ab"
      end
    end
  end

  def install
    bin.install "dega-server"
  end
end
